# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
    # config.ssh.private_key_path = "/home/etudiant/vagrant_dir/keys-vagrant/id_rsa_private"
    # config.ssh.forward_agent = true
    config.vm.define "silverport" do |silverport|
      silverport.vm.box = "ubuntu/focal64"
      silverport.vm.network "public_network", ip: "192.168.1.99"
      # silverport.vm.network "public_network", ip: "192.168.1.49",  use_dhcp_assigned_default_route: true
      silverport.vm.network "private_network", ip: "192.168.4.99",  virtualbox__intnet: true
      silverport.vm.network :forwarded_port, guest: 22, host: 2220

      
      silverport.vm.hostname = "silverport"
      silverport.vm.provider "virtualbox" do |vb|
        vb.name = "silverport"
        # vb.memory = "256"
        vb.memory = "2048"
      end
      silverport.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update -y


      sudo apt-get install -y fish


      SHELL
    end
  end


#   sudo apt-get install -y docker
